name: Build, Push to DockerHub & Deploy to Heroku

on:
  push:
    branches:
      - partStudent-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1. Login w push l Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bde-events-api:latest

      # 2. Installation dyal Heroku CLI 
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      # 3. Login, Push, w Release f Heroku
      - name: Login to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Build and Push Image to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: heroku container:push web -a ${{ secrets.HEROKU_APP_NAME }}

      - name: Release Image in Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
        